server:
  port: 9004
  
spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_ADDRESS:http//localhost:8094}
  application:
    name: sale-service  
  datasource:
    url:  ${CONFIG_SERVER_DB_URL:jdbc:mysql://localhost:3306/sale-service}?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: ${CONFIG_SERVER_DB_USERNAME:root}
    password: ${CONFIG_SERVER_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /swagger-ui.html


kafka:
  bootstrap:
    server:
      config: ${CONFIG_SERVER_KAFKA:localhost:19092} 
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true         