server:
  port: 9001
  
spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_ADDRESS:http//localhost:8094}
  application:
    name: sale-service  
  datasource:
    url: jdbc:mysql://localhost:3306/sale-service?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /swagger-ui.html


kafka:
  bootstrap:
    server:
      config: localhost:19092
          